name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: workflow/nix-shell-action@v3
        with:
          flakes-from-devshell: true
          script: |
            if [ -n "$(go fmt ./...)" ]; then
              echo "You must run 'go fmt ./...' to format your code before pushing."
              exit 1
            fi
