name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Use nix shell
        run: nix develop
      - name: Go fmt
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "You must run 'go fmt ./...' to format your code before pushing."
            exit 1
          fi
